---
bossbar-text: "&6FlameCore | &bMade by MoQi"
join-title: ""
notification-title: "Server"
notification-description: "Welcome to Server"
hub-world-name: "World"
teleporter-form-name: "Teleporter"
teleporter-form-button1: "Button1"
teleporter-form-button2: "Button2"
teleporter-form-button3: "Button3"
teleporter-form-command1: "pl"
teleporter-form-command2: "ver"
teleporter-form-command3: "pl"
information-text: "Nothing to say"
leave-message: "Thx for playing this server!"
server-ip: "play.example.net"